import assert from "assert";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { PublicKey, SystemProgram, type Keypair } from "@solana/web3.js";
import { startAnchor, BankrunProvider } from "anchor-bankrun";
import { Program, type Idl } from "@coral-xyz/anchor";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const BN = require("bn.js") as new (value: string | number) => { toNumber(): number };
type BNInstance = InstanceType<typeof BN>;

// Compiled IDL generated by `anchor build` (loaded at runtime to avoid Node import assertion)
const IDL = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "target", "idl", "voting.json"), "utf-8")
) as { address: string };

function u64ToLeBytes(value: bigint): Buffer {
  const buf = Buffer.alloc(8);
  buf.writeBigUInt64LE(value, 0);
  return buf;
}

describe("voting program (anchor-bankrun)", () => {
  let context: Awaited<ReturnType<typeof startAnchor>>;
  let provider: BankrunProvider;
  let program: Program<Idl>;
  let payer: Keypair;
  let programId: PublicKey;

  before(async () => {
    const anchorRoot = path.resolve(__dirname, "..");
    const soPath = path.join(anchorRoot, "target", "deploy", "voting.so");

    if (!fs.existsSync(soPath)) {
      throw new Error(
        `Missing compiled program at ${soPath}. Run 'cd anchor && anchor build'.`,
      );
    }

    context = await startAnchor(anchorRoot, [], []);
    provider = new BankrunProvider(context);
    payer = context.payer;
    programId = new PublicKey(IDL.address);
    // The JSON IDL produced by Anchor doesn't always line up with the TS types
    // (notably around PDA seed "kind"), so we cast through `unknown`.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    program = new Program(IDL as unknown as any, provider);
  });

  it("initializes a poll PDA", async () => {
    const pollIdValue = 1n;
    const pollId = new BN(pollIdValue.toString());
    const description = "Test poll";
    const pollStart = new BN("100");
    const pollEnd = new BN("200");

    // Rust: seeds=[poll_id.to_le_bytes().as_ref()]
    const [pollPda] = PublicKey.findProgramAddressSync(
      [u64ToLeBytes(pollIdValue)],
      programId,
    );

    type Methods = {
      initializePoll: (
        pollId: BNInstance,
        description: string,
        pollStart: BNInstance,
        pollEnd: BNInstance,
      ) => {
        accounts: (accounts: {
          signer: PublicKey;
          poll: PublicKey;
          systemProgram: PublicKey;
        }) => {
          signers: (signers: Keypair[]) => {
            rpc: () => Promise<string>;
          };
        };
      };
    };

    const methods = program.methods as unknown as Methods;
    await methods.initializePoll(pollId, description, pollStart, pollEnd)
      .accounts({
        signer: payer.publicKey,
        poll: pollPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([payer])
      .rpc();

    type PollAccount = {
      pollId: BNInstance;
      description: string;
      pollStart: BNInstance;
      pollEnd: BNInstance;
      candidateAmount: BNInstance;
      crunchyVotes: BNInstance;
      smoothVotes: BNInstance;
    };

    const accountNamespace = program.account as unknown as {
      poll: { fetch: (address: PublicKey) => Promise<PollAccount> };
    };
    const poll = await accountNamespace.poll.fetch(pollPda);

    assert.equal(poll.pollId.toNumber(), Number(pollIdValue));
    assert.equal(poll.description, description);
    assert.equal(poll.pollStart.toNumber(), 100);
    assert.equal(poll.pollEnd.toNumber(), 200);
    assert.equal(poll.candidateAmount.toNumber(), 0);
    assert.equal(poll.crunchyVotes?.toNumber?.() ?? 0, 0);
    assert.equal(poll.smoothVotes?.toNumber?.() ?? 0, 0);
  });
});

