[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
voting = "Hod4tDmSKRsoBBWtF8fFjTFugzp8kVE6dF3UaJsUPkX"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/kaliloulah1155/my-new-wallet.json"

[scripts]
test = "cargo test"

[hooks]
