[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "E4tUxezap8Gj42fHCxndPenNxNPARYVRyH6yhFABn3gL"

[programs.devnet]
voting = "E4tUxezap8Gj42fHCxndPenNxNPARYVRyH6yhFABn3gL"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/home/kaliloulah1155/my-new-wallet.json"

[scripts]
test = "cargo test"

[hooks]
